name: Build and Test CI

on:
  workflow_dispatch
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run test:unit
      - run: npm run test:acceptance
